### PR TITLE
Authentication with Devise Members Only collaborative project

### PR DESCRIPTION
**Pull request by Jmagero**
### Here is what we did

- [X] Designed a data model for this application having Users with simple identification attributes
- [X] -Connected the user's table to the post's table by the foreign key `:user_id`
- [X] -Added Devise gem.
- [X] -Created a Post model and a Posts controller and a corresponding resource in your Routes file.
- [X] - Used a `#before_action` to restrict access to the #new and #create methods to only users who are signed in
- [X] -Created the necessary helper methods in the ApplicationController
- [X] -Wrote a simple form in the app/views/posts/new.html.erb view to create a new Post
- [X] -Filled out the #index action of the PostsController and created the corresponding view
- [X] -Added logic in the Index view to display the author’s name, but only if a user is signed in

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

There are few changes to make :muscle: 

There should be no logic in your view files, rather, view-related logic should be encapsulated in View helpers (app/helpers/*_helper.rb). Use this [material](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) as a guide.

Also, here is the instruction from [pathright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png)

When you are done updating your view files, submit another code review form.


#### ``` Have a great day ``` :slightly_smiling_face: 


``` Uchechukwu Henry Inyama ```

**Comment by guirecordon** [comment]
Hey, Henry.
Thanks for all your time and help.
we removed all logic from our view files and created partials to be called from within our helper methods.

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

Thank you for applying the suggested changes.
You did a really good job :smile_cat: You can merge it now :+1: 

Good continuation :handshake: 

Mael FOSSO

**Comment by guirecordon** [comment]
Thank you, Mael.

**Pull request merged**
